# Generated by Django 3.2.7 on 2021-09-23 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Interaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connection', models.CharField(max_length=20, verbose_name='Название отношений')),
            ],
            options={
                'verbose_name': 'Взаимодействие',
                'verbose_name_plural': 'Взаимодействия',
            },
        ),
        migrations.CreateModel(
            name='Object',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object', models.CharField(help_text='max 21 символа', max_length=21, verbose_name='Название организации')),
                ('image_logo', models.ImageField(help_text='470х330', upload_to='static/images/interaction', verbose_name='Логотип')),
                ('con', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='interaction.interaction', verbose_name='Отношения')),
            ],
            options={
                'verbose_name': 'Организация',
                'verbose_name_plural': 'Организации',
            },
        ),
    ]
