# Generated by Django 3.2.7 on 2021-09-23 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interaction', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='object',
            old_name='object',
            new_name='name',
        ),
    ]
