# Generated by Django 3.2.7 on 2021-09-24 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interaction', '0002_rename_object_object_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='object',
            name='image_logo',
            field=models.ImageField(help_text='не более 200х200', upload_to='static/images/interaction', verbose_name='Логотип'),
        ),
    ]
