# Generated by Django 3.2.7 on 2021-09-19 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='700х467', upload_to='static/images/team', verbose_name='Фото')),
                ('l_name', models.CharField(max_length=15, verbose_name='Фмилия')),
                ('f_name', models.CharField(max_length=15, verbose_name='Имя')),
                ('patronymic', models.CharField(max_length=15, verbose_name='Отчество')),
                ('post', models.CharField(help_text='max XXX символ', max_length=20, verbose_name='Должность/род деятельности')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Команда',
                'verbose_name_plural': 'Команда',
            },
        ),
    ]
