# Generated by Django 3.2.7 on 2021-09-21 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='team',
            options={'verbose_name': 'Сотрудник', 'verbose_name_plural': 'Сотрудники'},
        ),
        migrations.AlterField(
            model_name='team',
            name='description',
            field=models.TextField(help_text='250 символов', verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='team',
            name='post',
            field=models.CharField(help_text='max 50 символ', max_length=50, verbose_name='Должность/род деятельности'),
        ),
    ]
