# Generated by Django 3.2.7 on 2021-09-21 20:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='theme',
            field=models.CharField(choices=[('Заключение договора', 'Заключение договора'), ('Отзыв', 'Отзыв'), ('Иное...', 'Иное...')], default=django.utils.timezone.now, max_length=20, verbose_name='Тема сообщения'),
            preserve_default=False,
        ),
    ]
